CREATE TABLE [dbo].[Users]
(
	[Id] INT IDENTITY (1, 1) NOT NULL, 
	[FirstName] NVARCHAR(256) NOT NULL,
	[SureName] NVARCHAR(256) NOT NULL,
	[Email] NVARCHAR(256) NOT NULL,
	[PhoneNumber] NVARCHAR(256) NOT NULL,
	[Position] NVARCHAR(256) NOT NULL,
	CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC)
)
